build: false

environment:
  matrix:
      - PYTHON_HOME: "C:/Python27"
        PYTHON_VERSION: 2.7
        RL: 32
      - PYTHON_HOME: "C:/Python27"
        PYTHON_VERSION: 2.7
        RL: 33

      - PYTHON_HOME: "C:/Python35"
        PYTHON_VERSION: 3.5
        RL: 32
      - PYTHON_HOME: "C:/Python35"
        PYTHON_VERSION: 3.5
        RL: 33

install:
  - cmd: |
        set TOX_ENV=py%PYTHON_VERSION%-rl%RL%
        echo %TOX_ENV%
        "%PYTHON_HOME%/python.exe" -m pip install --upgrade pip
        "%PYTHON_HOME%/Scripts/pip.exe" install tox coveralls

before_test:
    - cmd: |
        "%PYTHON_HOME%/Scripts/pip.exe" list

# command to run tests
test_script:
  - cmd: |
        %PYTHON_HOME%\Scripts\tox -e %TOX_ENV% -c tox.appveyor.ini
